from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
BRANDS_DIR = ROOT / "backend" / "app" / "config" / "brands"


class BrandVideoRenderer:
    """Apply the selected brand identity to an already rendered MP4."""

    def __init__(self, brand_id: str = "afham_wadhak") -> None:
        self.brand_id = brand_id
        self.config_path = BRANDS_DIR / f"{brand_id}.json"
        self.config = json.loads(self.config_path.read_text(encoding="utf-8"))
        if self.config.get("brand_id") != brand_id:
            raise ValueError(f"Brand config id mismatch: {self.config.get('brand_id')} != {brand_id}")
        if shutil.which("ffmpeg") is None:
            raise RuntimeError("FFMPEG_NOT_FOUND")

    def _asset(self, name: str) -> Path:
        folder = self.config.get("file_structure", {}).get("brand_folder", f"assets/branding/{self.brand_id}/")
        path = ROOT / Path(folder) / name
        if not path.is_file():
            raise FileNotFoundError(path)
        return path

    def apply(self, source: str | Path, output: str | Path, width: int, height: int, fps: int) -> str:
        source_path = Path(source)
        output_path = Path(output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        intro = self._asset("intro.mp4")
        outro = self._asset("outro.mp4")
        watermark = self._asset("watermark.png")
        opacity = float(self.config.get("watermark", {}).get("opacity", 0.35))
        opacity = max(0.0, min(1.0, opacity))

        filter_complex = (
            f"[0:v]fps={fps},scale={width}:{height}:force_original_aspect_ratio=decrease,"
            f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1,format=yuv420p[v0];"
            f"[1:v]fps={fps},scale={width}:{height}:force_original_aspect_ratio=decrease,"
            f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1,format=yuv420p[vi];"
            f"[2:v]fps={fps},scale={width}:{height}:force_original_aspect_ratio=decrease,"
            f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1,format=yuv420p[vo];"
            f"[3:v]format=rgba,colorchannelmixer=aa={opacity}[wm];"
            f"[v0][wm]overlay=W-w-36:H-h-36[vc];"
            f"[vi][1:a]concat=n=1:v=1:a=1[ia];"
            f"[vc][0:a]concat=n=1:v=1:a=1[ca];"
            f"[vo][2:a]concat=n=1:v=1:a=1[oa];"
            f"[ia][ca][oa]concat=n=3:v=1:a=0[vout];"
            f"[1:a][0:a][2:a]concat=n=3:v=0:a=1[aout]"
        )

        # The intro/outro assets generated by the brand build are guaranteed to
        # contain stereo AAC audio. The source render may also contain audio.
        # FFmpeg's concat filter handles the three normalized segments.
        subprocess.run(
            [
                "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                "-i", str(source_path),
                "-i", str(intro),
                "-i", str(outro),
                "-loop", "1", "-i", str(watermark),
                "-filter_complex", filter_complex,
                "-map", "[vout]", "-map", "[aout]",
                "-c:v", "libx264", "-preset", "medium", "-crf", "20",
                "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "192k",
                "-movflags", "+faststart",
                "-metadata", f"brand_id={self.brand_id}",
                "-metadata", f"brand_name={self.config.get('brand_name_en', self.brand_id)}",
                str(output_path),
            ],
            check=True,
        )
        return str(output_path)
