from __future__ import annotations
from abc import ABC, abstractmethod
from .locations import LocationProfile

class LocationRepository(ABC):
    @abstractmethod
    def create(self, location: LocationProfile) -> LocationProfile: ...
    @abstractmethod
    def get(self, location_id: str) -> LocationProfile | None: ...
    @abstractmethod
    def update(self, location: LocationProfile) -> LocationProfile: ...
    @abstractmethod
    def delete(self, location_id: str) -> bool: ...
    @abstractmethod
    def list(self, *, project_id: str | None = None, query: str | None = None, limit: int = 100) -> list[LocationProfile]: ...
