from abc import ABC, abstractmethod
from .assets import Asset, AssetStatus
from .jobs import GenerationJob, JobStatus
from .projects import Episode, Project, Scene, Shot


class ProjectRepository(ABC):
    @abstractmethod
    def create(self, project: Project) -> Project: ...
    @abstractmethod
    def get(self, project_id: str) -> Project | None: ...


class EpisodeRepository(ABC):
    @abstractmethod
    def create(self, episode: Episode) -> Episode: ...
    @abstractmethod
    def get(self, episode_id: str) -> Episode | None: ...


class SceneRepository(ABC):
    @abstractmethod
    def create(self, scene: Scene) -> Scene: ...
    @abstractmethod
    def get(self, scene_id: str) -> Scene | None: ...


class ShotRepository(ABC):
    @abstractmethod
    def create(self, shot: Shot) -> Shot: ...
    @abstractmethod
    def get(self, shot_id: str) -> Shot | None: ...


class JobRepository(ABC):
    @abstractmethod
    def create(self, job: GenerationJob) -> GenerationJob: ...
    @abstractmethod
    def get(self, job_id: str) -> GenerationJob | None: ...
    @abstractmethod
    def update(self, job: GenerationJob) -> GenerationJob: ...
    @abstractmethod
    def list_by_parent(self, parent_job_id: str) -> list[GenerationJob]: ...
    @abstractmethod
    def list(self, *, project_id: str | None = None, status: JobStatus | None = None, limit: int = 50) -> list[GenerationJob]: ...


class AssetRepository(ABC):
    @abstractmethod
    def create(self, asset: Asset) -> Asset: ...
    @abstractmethod
    def get(self, asset_id: str) -> Asset | None: ...
    @abstractmethod
    def update(self, asset: Asset) -> Asset: ...
    @abstractmethod
    def list(self, *, project_id: str | None = None, asset_type: str | None = None, status: AssetStatus | None = None, limit: int = 100) -> list[Asset]: ...


class ProviderRunRepository(ABC):
    @abstractmethod
    def create(self, run): ...
    @abstractmethod
    def complete(self, run): ...
    @abstractmethod
    def get(self, run_id: str): ...
    @abstractmethod
    def list_for_job(self, job_id: str, limit: int = 100): ...
